// MatSpark – Mock Data

export const SITE = {
  name: 'MathSpark',
  tagline: 'Ignite Your Math Skills',
  description: 'Sri Lanka\'s most result-oriented online mathematics platform for Grades 6–11.',
  phone: '+94 112 902 405',
  whatsapp: '94112902405',
  email: 'info@mathspark.lk',
  facebook: 'https://facebook.com/mathspark',
  youtube: 'https://youtube.com/@mathspark',
  instagram: 'https://instagram.com/mathspark',
  twitter: 'https://twitter.com/mathspark',
};

export const STATS = [
  { value: 5200, suffix: '+', label: 'Active Students' },
  { value: 98,   suffix: '%', label: 'A-Pass Rate' },
  { value: 12,   suffix: '+', label: 'Years Experience' },
  { value: 1800, suffix: '+', label: 'Video Lessons' },
];

export const GRADES = [
  { id: 6,  label: 'Grade 06', subjects: ['Maths (Sinhala)', 'Maths (English)'] },
  { id: 7,  label: 'Grade 07', subjects: ['Maths (Sinhala)', 'Maths (English)'] },
  { id: 8,  label: 'Grade 08', subjects: ['Maths (Sinhala)', 'Maths (English)'] },
  { id: 9,  label: 'Grade 09', subjects: ['Maths (Sinhala)', 'Maths (English)'] },
  { id: 10, label: 'Grade 10', subjects: ['Maths (Sinhala)', 'Maths (English)', 'English'] },
  { id: 11, label: 'Grade 11', subjects: ['Maths (Sinhala)', 'Maths (English)'] },
];

export const COURSES = [
  {
    id: 1,
    title: 'Grade 10 – Sinhala Medium Maths',
    titleSi: '10 ශ්‍රේණිය – සිංහල මාධ්‍ය ගණිතය',
    grade: 10,
    medium: 'sinhala',
    lessons: 363,
    students: 1240,
    packs: 76,
    price: 2000,
    currency: 'LKR',
    isFree: false,
    isPopular: true,
    thumbnail: '/images/courses/grade10-si.jpg',
    badge: 'Most Popular',
    badgeColor: '#FF6B00',
    schedule: 'Every Saturday 3:00 PM',
    description: 'Comprehensive Grade 10 Mathematics covering the 2026 new syllabus. Live interactive sessions every Saturday with full recordings available anytime.',
    instructor: 'Ishan Maduranga',
    topics: ['Algebra', 'Geometry', 'Statistics', 'Trigonometry', 'Sets & Functions'],
  },
  {
    id: 2,
    title: 'Grade 11 – Sinhala Medium Maths',
    titleSi: '11 ශ්‍රේණිය – සිංහල මාධ්‍ය ගණිතය',
    grade: 11,
    medium: 'sinhala',
    lessons: 290,
    students: 980,
    packs: 52,
    price: 2000,
    currency: 'LKR',
    isFree: false,
    isPopular: true,
    thumbnail: '/images/courses/grade11-si.jpg',
    badge: 'O/L Focused',
    badgeColor: '#7B2FFF',
    schedule: 'Every Sunday 2:00 PM',
    description: 'O/L focused Grade 11 Maths with past paper analysis, exam tips, and intensive revision sessions.',
    instructor: 'Ishan Maduranga',
    topics: ['Advanced Algebra', 'Calculus Basics', 'Probability', 'Coordinate Geometry'],
  },
  {
    id: 3,
    title: 'Grade 06 – Sinhala Medium Maths',
    titleSi: '6 ශ්‍රේණිය – සිංහල මාධ්‍ය ගණිතය',
    grade: 6,
    medium: 'sinhala',
    lessons: 228,
    students: 860,
    packs: 66,
    price: 2000,
    currency: 'LKR',
    isFree: false,
    isPopular: true,
    thumbnail: '/images/courses/grade06-si.jpg',
    badge: 'New Syllabus',
    badgeColor: '#00C896',
    schedule: 'Every Sunday 3:30 PM',
    description: 'Build a rock-solid foundation in Maths from Grade 6. Fun, interactive lessons designed for young learners.',
    instructor: 'Ishan Maduranga',
    topics: ['Number Systems', 'Fractions', 'Basic Algebra', 'Shapes & Measurement'],
  },
  {
    id: 4,
    title: 'Grade 07 – Sinhala Medium Maths',
    titleSi: '7 ශ්‍රේණිය – සිංහල මාධ්‍ය ගණිතය',
    grade: 7,
    medium: 'sinhala',
    lessons: 242,
    students: 720,
    packs: 60,
    price: 1500,
    currency: 'LKR',
    isFree: false,
    isPopular: false,
    thumbnail: '/images/courses/grade07-si.jpg',
    badge: null,
    badgeColor: null,
    schedule: 'Every Monday 5:30 PM',
    description: 'Grade 7 Maths with step-by-step explanations. Perfect for students who want to build confidence in mathematics.',
    instructor: 'Ishan Maduranga',
    topics: ['Integers', 'Ratios', 'Basic Geometry', 'Data Handling'],
  },
  {
    id: 5,
    title: 'Grade 08 – Sinhala Medium Maths',
    titleSi: '8 ශ්‍රේණිය – සිංහල මාධ්‍ය ගණිතය',
    grade: 8,
    medium: 'sinhala',
    lessons: 255,
    students: 650,
    packs: 48,
    price: 1500,
    currency: 'LKR',
    isFree: false,
    isPopular: false,
    thumbnail: '/images/courses/grade08-si.jpg',
    badge: null,
    badgeColor: null,
    schedule: 'Every Wednesday 5:00 PM',
    description: 'Grade 8 Mathematics structured for the new syllabus with special focus on problem-solving techniques.',
    instructor: 'Ishan Maduranga',
    topics: ['Linear Equations', 'Quadrilaterals', 'Percentages', 'Statistics'],
  },
  {
    id: 6,
    title: 'Grade 09 – Sinhala Medium Maths',
    titleSi: '9 ශ්‍රේණිය – සිංහල මාධ්‍ය ගණිතය',
    grade: 9,
    medium: 'sinhala',
    lessons: 275,
    students: 590,
    packs: 42,
    price: 2000,
    currency: 'LKR',
    isFree: false,
    isPopular: false,
    thumbnail: '/images/courses/grade09-si.jpg',
    badge: null,
    badgeColor: null,
    schedule: 'Every Friday 4:00 PM',
    description: 'Prepare for the leap to Grade 10 with comprehensive Grade 9 Maths. Special emphasis on analytical thinking.',
    instructor: 'Ishan Maduranga',
    topics: ['Surds', 'Matrices', 'Trigonometry Intro', 'Sets'],
  },
  {
    id: 7,
    title: 'Grade 10 – English Medium Maths',
    titleSi: 'Grade 10 – English Medium Maths',
    grade: 10,
    medium: 'english',
    lessons: 180,
    students: 430,
    packs: 30,
    price: 2500,
    currency: 'LKR',
    isFree: false,
    isPopular: false,
    thumbnail: '/images/courses/grade10-en.jpg',
    badge: 'English Medium',
    badgeColor: '#0052FF',
    schedule: 'Every Thursday 6:00 PM',
    description: 'English Medium Grade 10 Maths with bilingual explanations. Ideal for international school and English stream students.',
    instructor: 'Ishan Maduranga',
    topics: ['Algebra', 'Geometry', 'Statistics', 'Number Theory'],
  },
  {
    id: 8,
    title: 'Grade 09 – English Medium Maths',
    titleSi: 'Grade 09 – English Medium Maths',
    grade: 9,
    medium: 'english',
    lessons: 160,
    students: 310,
    packs: 24,
    price: 2500,
    currency: 'LKR',
    isFree: false,
    isPopular: false,
    thumbnail: '/images/courses/grade09-en.jpg',
    badge: 'English Medium',
    badgeColor: '#0052FF',
    schedule: 'Every Tuesday 5:30 PM',
    description: 'English Medium Grade 9 Maths — clear, concise lessons in English for a stronger foundation.',
    instructor: 'Ishan Maduranga',
    topics: ['Algebra', 'Trigonometry', 'Geometry', 'Statistics'],
  },
];

export const POPULAR_COURSES = COURSES.filter(c => c.isPopular);

export const STORE_ITEMS = [
  {
    id: 1,
    title: 'Grade 10 Maths Revision Book – 2026',
    price: 850,
    originalPrice: 1200,
    currency: 'LKR',
    type: 'physical',
    thumbnail: '/images/store/book-grade10.jpg',
    description: 'Complete revision book with past papers, model answers, and topic summaries.',
    inStock: true,
    badge: 'Best Seller',
  },
  {
    id: 2,
    title: 'Grade 11 O/L Maths Formula Sheet',
    price: 150,
    originalPrice: 250,
    currency: 'LKR',
    type: 'digital',
    thumbnail: '/images/store/formula-sheet.jpg',
    description: 'Printable A3 formula sheet covering all O/L Maths topics. Instant download.',
    inStock: true,
    badge: 'Digital',
  },
  {
    id: 3,
    title: 'Grade 6-8 Foundation Maths Workbook',
    price: 650,
    originalPrice: 900,
    currency: 'LKR',
    type: 'physical',
    thumbnail: '/images/store/workbook-foundation.jpg',
    description: 'Hands-on workbook for Grade 6-8 students with exercises and answer keys.',
    inStock: true,
    badge: null,
  },
  {
    id: 4,
    title: 'O/L Maths Past Papers (2018–2025)',
    price: 1200,
    originalPrice: 1800,
    currency: 'LKR',
    type: 'physical',
    thumbnail: '/images/store/past-papers.jpg',
    description: 'Complete set of O/L Mathematics past papers with structured answers.',
    inStock: false,
    badge: 'Out of Stock',
  },
];

export const INSTRUCTORS = [
  {
    id: 1,
    name: 'Ishan Maduranga',
    title: 'Lead Mathematics Instructor',
    experience: '12+ Years',
    students: '5000+',
    bio: 'Sri Lanka\'s most popular online Maths teacher. Known for making complex concepts simple and enjoyable. B.Sc in Mathematics, University of Colombo.',
    avatar: '/images/instructors/ishara.jpg',
    courses: 8,
    rating: 4.9,
    reviews: 3200,
    specialization: 'O/L Mathematics (Sinhala & English Medium)',
    social: {
      youtube: '#',
      facebook: '#',
      instagram: '#',
    },
  },
];

export const TESTIMONIALS = [
  {
    id: 1,
    name: 'Kavindi Perera',
    grade: 'Grade 11 Student',
    avatar: '/images/testimonials/kavindi.jpg',
    rating: 5,
    text: 'I got an A for O/L Maths thanks to MathSpark! The classes are so clear and the recordings help me revise at my own pace.',
    result: 'A Pass – O/L 2025',
  },
  {
    id: 2,
    name: 'Tharindu Silva',
    grade: 'Grade 10 Student',
    avatar: '/images/testimonials/tharindu.jpg',
    rating: 5,
    text: 'Best online Maths class in Sri Lanka. Sir explains everything step by step. I improved from a C to an A in just 3 months!',
    result: 'A Pass – Term Exam',
  },
  {
    id: 3,
    name: 'Sithmi Fernando',
    grade: 'Grade 9 Student',
    avatar: '/images/testimonials/sithmi.jpg',
    rating: 5,
    text: 'I used to hate Maths. Now it\'s my favourite subject! The interactive sessions and WhatsApp support made all the difference.',
    result: 'Top of Class',
  },
  {
    id: 4,
    name: 'Dinesh Bandara',
    grade: 'Grade 11 Parent',
    avatar: '/images/testimonials/dinesh.jpg',
    rating: 5,
    text: 'My daughter went from failing Maths to getting an A. The value for money is incredible. Highly recommend to every parent.',
    result: 'Child – A Pass O/L',
  },
];

export const WHY_MATSPARK = [
  {
    icon: '🎥',
    title: 'Live Interactive Classes',
    description: 'Join real-time classes with your teacher and classmates. Ask questions, get instant answers.',
  },
  {
    icon: '📹',
    title: 'All Recordings Available',
    description: 'Never miss a class. All sessions are recorded and available 24/7 on your dashboard.',
  },
  {
    icon: '📱',
    title: 'WhatsApp Support',
    description: 'Direct WhatsApp access to your instructor. Get help when you need it, instantly.',
  },
  {
    icon: '📊',
    title: 'Progress Tracking',
    description: 'Track your performance with detailed analytics, quiz scores, and lesson completion.',
  },
  {
    icon: '🇱🇰',
    title: 'Sinhala & English Medium',
    description: 'Classes available in both Sinhala and English. Learn in the language you\'re most comfortable with.',
  },
  {
    icon: '💰',
    title: 'Affordable Pricing',
    description: 'Premium education at an affordable price. Starting from just LKR 1,500/month.',
  },
];

export const NAV_LINKS = [
  { label: 'Home',      href: '/',         icon: 'home' },
  { label: 'Classes',   href: '/courses',  icon: 'classes' },
  { label: 'Timetable', href: '/timetable',icon: 'timetable' },
  { label: 'MCQ Tests', href: '/exams',    icon: 'exams' },
  { label: 'Store',     href: '/store',    icon: 'store' },
  { label: 'Results',   href: '/results',  icon: 'results' },
  { label: 'Tute',      href: '/tute',     icon: 'tute' },
  { label: 'Tracking',  href: '/tracking', icon: 'tracking' },
  { label: 'Contact',   href: '/contact',  icon: 'contact' },
];

